version: "3"
services:
  nginx:
    image: nginx:1.17
    ports:
      - 8000:8000
    depends_on:
      - app
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./scripts/dev/Dockerfile
    environment:
      - PORT=8000
      - APP_URL=http://app:8000
    volumes:
      - ./src:/github.com/nawajar/duck/src